language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=Django==1.11.3

install:
  - pip install $DJANGO M2Crypto
script:
  - python runtests.py
notifications:
  email:
    recipients:
      - baguage@gmail.com
    on_success: always
    on_failure: always